-- ArXiv Papers Bot - Initial Database Schema
-- This migration sets up the arxiv_papers table with vector search capabilities
-- NOTE: This is designed to coexist with other bot tables in a shared database

-- 1. Enable the Vector extension for semantic search (shared across all bots)
create extension if not exists vector;

-- 2. Create the arxiv_papers table (prefixed to avoid conflicts)
create table arxiv_papers (
  id bigint generated by default as identity primary key,
  arxiv_id text unique not null,
  title text not null,
  abstract text,
  authors text[], -- Array of author names
  published_at timestamp with time zone,
  url text,

  -- AI Enrichment (generated by Gemini)
  impact_score int check (impact_score >= 1 and impact_score <= 10), -- 1-10 score
  summary text, -- One sentence TL;DR
  tags text[], -- List of categories (e.g., ["CV", "LLM", "Transformers"])

  -- Vector Embeddings (384 dimensions for all-MiniLM-L6-v2)
  embedding vector(384),

  -- Bot State Management
  posted_to_discord boolean default false,
  last_posted_at timestamp with time zone,

  -- Metadata
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create indexes for performance
create index arxiv_papers_arxiv_id_idx on arxiv_papers(arxiv_id);
create index arxiv_papers_published_at_idx on arxiv_papers(published_at desc);
create index arxiv_papers_posted_to_discord_idx on arxiv_papers(posted_to_discord) where posted_to_discord = false;
create index arxiv_papers_impact_score_idx on arxiv_papers(impact_score desc);

-- 4. Create a vector similarity index using HNSW (Hierarchical Navigable Small World)
-- This dramatically speeds up vector similarity searches
create index arxiv_papers_embedding_idx on arxiv_papers
using hnsw (embedding vector_cosine_ops)
with (m = 16, ef_construction = 64);

-- 5. Enable Row Level Security (RLS)
alter table arxiv_papers enable row level security;

-- 6. Create RLS policies
-- Allow public read access (for the Discord bot with anon key)
create policy "arxiv_public_read_access"
  on arxiv_papers for select
  using (true);

-- Allow service role to write (for the GitHub Actions job)
create policy "arxiv_service_role_write_access"
  on arxiv_papers for all
  using (auth.role() = 'service_role');

-- 7. Create a function to automatically update the updated_at timestamp
-- Only create if it doesn't exist (shared function with other bots)
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- 8. Create trigger for auto-updating updated_at
create trigger update_arxiv_papers_updated_at
  before update on arxiv_papers
  for each row
  execute function update_updated_at_column();

-- 9. Create a semantic search function for vector similarity search
-- This will be called by the Discord bot's /search command
create or replace function arxiv_match_papers (
  query_embedding vector(384),
  match_threshold float default 0.3,
  match_count int default 10
)
returns table (
  id bigint,
  arxiv_id text,
  title text,
  summary text,
  impact_score int,
  tags text[],
  url text,
  published_at timestamp with time zone,
  similarity float
)
language sql stable
as $$
  select
    arxiv_papers.id,
    arxiv_papers.arxiv_id,
    arxiv_papers.title,
    arxiv_papers.summary,
    arxiv_papers.impact_score,
    arxiv_papers.tags,
    arxiv_papers.url,
    arxiv_papers.published_at,
    1 - (arxiv_papers.embedding <=> query_embedding) as similarity
  from arxiv_papers
  where
    arxiv_papers.embedding is not null
    and 1 - (arxiv_papers.embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
$$;

-- 10. Create a full-text search function as a fallback
-- Useful if vector search returns no results
create or replace function arxiv_search_papers_fulltext (
  search_query text,
  match_count int default 10
)
returns table (
  id bigint,
  arxiv_id text,
  title text,
  summary text,
  impact_score int,
  tags text[],
  url text,
  published_at timestamp with time zone
)
language sql stable
as $$
  select
    id,
    arxiv_id,
    title,
    summary,
    impact_score,
    tags,
    url,
    published_at
  from arxiv_papers
  where
    title ilike '%' || search_query || '%'
    or abstract ilike '%' || search_query || '%'
    or summary ilike '%' || search_query || '%'
  order by
    impact_score desc nulls last,
    published_at desc
  limit match_count;
$$;

-- 11. Create a function to get unposted high-impact papers
-- Used by the Discord bot's background task
create or replace function arxiv_get_unposted_papers (
  min_impact_score int default 7
)
returns table (
  id bigint,
  arxiv_id text,
  title text,
  summary text,
  impact_score int,
  tags text[],
  url text,
  published_at timestamp with time zone
)
language sql stable
as $$
  select
    id,
    arxiv_id,
    title,
    summary,
    impact_score,
    tags,
    url,
    published_at
  from arxiv_papers
  where
    posted_to_discord = false
    and impact_score >= min_impact_score
  order by published_at desc
  limit 20; -- Safety limit
$$;
